name: "Interactive Pinout Generator"
description: "Generates interactive pinouts from mappings"
author: "dave@holdemanenterprises.com"

inputs:
  mapping-path:
    required: true
    description: |
      Location of mapping file
      You can use globs to match multiple files, for example:
      ./boards/*/connectors/*.yaml
  warnings:
    required: false
    description: |
      Set to "skip" to skip to the next mapping file,
      "notice" to warn on the Actions page,
      or "error" to fail the workflow step.
    default: "false"
  warning-no-cid:
    required: false
    description: |
      Set to "skip" to skip to the next mapping file,
      "notice" to warn on the Actions page,
      or "error" to fail the workflow step.
    default: "unset"
  warning-no-image:
    required: false
    description: |
      Set to "skip" to skip to the next mapping file,
      "notice" to warn on the Actions page,
      or "error" to fail the workflow step.
    default: "unset"
  warning-no-connectors:
    required: false
    description: |
      Set to "skip" to skip to the next mapping file,
      "notice" to warn on the Actions page,
      or "error" to fail the workflow step.
    default: "unset"
  warning-dupe:
    required: false
    description: |
      Set to "skip" to skip to the next mapping file,
      "notice" to warn on the Actions page,
      or "error" to fail the workflow step.
    default: "unset"
  columns:
    required: true
    description: |
      A JSON mapping of column IDs to human-readable names.
      "pin" column is assumed to be pin numbers
      "type" column can be used to group pins by type.
  print-columns:
    required: true
    description: |
      A JSON array of column IDs that will be visible in print mode. Provide at least one.
      The "pin" column is always visible.
  info-column:
    required: false
    description: |
      A column whose value will be displayed when hovering over a pin.
  templates:
    required: false
    description: |
      A JSON mapping of strings to fields which will replace them.
  colors:
    required: false
    description: |
      A JSON mapping of pin "type" fields to CSS colors.
  debug:
    required: false
    description: |
      Don't minify, and add some logging to the JS
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    MAPPING_PATH: ${{ inputs.mapping-path }}
    WARNINGS: ${{ inputs.warnings }}
    WARNING_NO_CID: ${{ inputs.warning-no-cid }}
    WARNING_NO_IMAGE: ${{ inputs.warning-no-image }}
    WARNING_NO_CONNECTORS: ${{ inputs.warning-no-connectors }}
    WARNING_DUPE: ${{ inputs.warning-dupe }}
    COLS: ${{ inputs.columns }}
    PRINT_COLS: ${{ inputs.print-columns }}
    INFO_COL: ${{ inputs.info-column }}
    TEMPLATES: ${{ inputs.templates }}
    COLORS: ${{ inputs.colors }}
    DEBUG: ${{ inputs.debug }}
branding:
  icon: "cpu"
  color: "orange"
